/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hud.selects.personalizados;

import hud.selects.*;
import hud.festa.*;
import hud.cliente.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import sgbdCommands.ClienteDB;
import sgbdCommands.ConnectionSGBD;

/**
 *
 * @author thiago
 */
public class TelaSelecionarP6 extends javax.swing.JInternalFrame {
    ArrayList<Cliente> clientes;
    
    /**
     * Creates new form TelaInicialInterna
     */
    public TelaSelecionarP6() {
        initComponents();
    }
    
    public void listarP6() {
        DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
        Connection con = null;
        try {
            con = ConnectionSGBD.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT F.NRO_REGISTRO, COUNT(*) AS QTDE_BOLOS_PEDIDOS, SUM(B.PRECO) AS SOMA_PRECO_BOLOS FROM FESTA F" +
                                            "    JOIN BOLO_FESTA BF ON F.NRO_REGISTRO = BF.FESTA_NRO_REGISTRO" +
                                            "    JOIN BOLO B ON BF.BOLO_NOME = B.NOME " +
                                            "    GROUP BY F.NRO_REGISTRO HAVING COUNT(*) > 1 " +
                                            "    ORDER BY F.NRO_REGISTRO ");

            while (rs.next()) {
                t.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getDouble(3)});
            }
            
            //con.commit(); //depois ver de desabilitar commit automatico, mas por enquanto eh melhor assim
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            System.out.println("Erro no SelecionarP6");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Erro no SelecionarP6");
        }
        
        ConnectionSGBD.CloseConnection(con);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Para todas as festas de casamento com pedidos de dois ou mais bolos, mostrar seu numero ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FESTA NRO REG", "QTD BOLOS PEDIDOS", "SOMA PRECOS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("tabelacliente");

        jLabel2.setText("de registro e mostrar a soma total dos precos de todos os bolos destas festas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
