/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hud.selects;

import hud.festa.*;
import hud.cliente.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Festa;
import sgbdCommands.FestaDB;

/**
 *
 * @author thiago
 */
public class TelaSelecionarTFesta extends javax.swing.JInternalFrame {
    ArrayList<Festa> festas;
    
    /**
     * Creates new form TelaInicialInterna
     */
    public TelaSelecionarTFesta() {
        initComponents();
    }
    
    public void listarClientes() {
        FestaDB festadb = new FestaDB();
        festas = festadb.Festa_SelectAll();
        
        DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
        
        for (Festa f : festas) {
            t.addRow(new Object[]{f.getNroRegistro(), f.getNroConvidados(), f.getEndereco(), f.getPrecoFesta(), f.getTipo(), f.getDataHora(), f.getPrecoTotal(), f.getClienteCpf()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("TELA INICIAL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO_REGISTRO", "NRO_CONVIDADOS", "ENDERECO", "PRECO_FESTA", "TIPO", "DATA_HORA", "PRECO_TOTAL", "CLIENTE_CPF"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
